### ISSUE TITLE
Clarify compatibility with older AEM versions in readme

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-core-wcm-components#10]
Are the core-wcm-components really only compatible with AEM 6.3? What about older version. It would be good to add a dedicated section "Prerequisites" to the readme, which does not only outline the build requirements but also the runtime requirements.

**Comment by gabrielwalt** [comment]
Great comment, thanks for the feedback and keep it coming!

The components' logic require SlingModel 1.3 and therefore wouldn't work on AEM 6.2. We'll add that information to the readme.

We might consider a 6.2 FP to back-port the specific 6.3 dependencies that these components have. However, if you'd like this to happen, I'd invite you to open a formal support request, which would to prioritize it.

**Comment by kwin** [comment]
But Sling Models 1.3 can be deployed without any problems on at least AEM 6.2.

**Comment by gabrielwalt** [comment]
Correct, you can deploy Sling Models 1.3 yourself too, but it might also be helpful to use an official FP for that. Also, there might as well be other dependencies. One of them is that the text and image components allow the RTE and in-place image editor to be configured via the design dialog. But that capability could be hidden from the dialogs if on 6.2.

Bottomline: we didn't test it with 6.2 yet. The components might mostly work, and it would definitely be worth investigating what's missing to also support 6.2. If easy enough, that would be nice.

**Comment by bpauli** [comment]
System requirements added to the README.
