### ISSUE TITLE
Image Component: Fileupload widget no more showing thumbnail, Clear options unavailable

### ISSUE THREAD

**Issue by tnebe** [Adobe-Marketing-Cloud/aem-core-wcm-components#101]
When using **AEM Core WCM Image component** with provided dialog, it only accepts rasterized images by `mimeTypes` change of @kwin in https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/pull/32/files

![image](https://user-images.githubusercontent.com/31446861/35617768-5558703c-0679-11e8-8667-9cb1e51b73df.png)

With this change, the fileupload widget is no more able to create a thumbnail, as the according script only accepts `image `as mimeType in **/libs/cq/gui/components/authoring/dialog/fileupload/render.jsp** [AEM 6.3.0.2]:

```
/* L214 */ boolean hasImageMimeType = Arrays.asList(mimeTypes).contains("image");
/* L215 */ ...
```

According Daycare ticket has been raised and already confimed by Adobe as a product bug in **Ticket ID 139755** and will now be fixed with **AEM 6.4**. The change could be applied earlier by overlaying **/libs/cq/gui/components/authoring/dialog/fileupload/render.jsp** and will look like:

```
...
         Node thumbnailNode = res.adaptTo(Node.class);
         long cacheKiller = UIHelper.getCacheKiller(thumbnailNode);
 
-        boolean hasImageMimeType = Arrays.asList(mimeTypes).contains("image");
-        boolean hasVideoMimeType = Arrays.asList(mimeTypes).contains("video");
+        boolean hasImageLikeMimeType = false;
+        boolean hasVideoLikeMimeType = false;
 
+        for (String mimeType : mimeTypes) {
+            hasImageLikeMimeType = hasImageLikeMimeType || mimeType.startsWith("image");
+            hasVideoLikeMimeType = hasVideoLikeMimeType || mimeType.startsWith("video");
+        }
+
         if (assetResource != null || StringUtils.isNotEmpty(resourceFileName)) {
-            if (hasImageMimeType || hasVideoMimeType) {
+            if (hasImageLikeMimeType || hasVideoLikeMimeType) {
                 if (assetResource != null) {
                     // For a DAM image reference: get a web rendition
                     // For a DAM video reference: get a thumbnail rendition
                     Asset asset = assetResource.adaptTo(Asset.class);
                     if (asset != null) {
                         final Rendition rendition;
 
-                        if (hasVideoMimeType) {
+                        if (hasVideoLikeMimeType) {
                             rendition = asset.getRendition(THUMBNAIL_RENDITION_NAME);
                         } else {
                             rendition = asset.getRendition(new WCMRenditionPicker());
...
```

Nevertheless raising an issue here also, as this is a bad behaviour coming with introducing WCM Core Image Component and like to discuss possible solutions.

Maybe there is an approach for accepting any type of image because SVG´s are not able to use with current solution or just adding a hint in the image component README file.

Thanks!

**Comment by henrykuijpers** [comment]
Actually, letting the "mimeTypes"-property still include "image" as well, should not really be an issue. WDYT?

**Comment by henrykuijpers** [comment]
Eehhrrr, yes, indeed. These components still have to work on aem versions lower than 6.4...
