### ISSUE TITLE
Resource `cq/cloudconfig/components/scripttags/header` missing

### ISSUE THREAD

**Issue by hegarg** [Adobe-Marketing-Cloud/aem-core-wcm-components#102]
Hi Team,
Release version : 2.0.0

Under Page component (v2) 
`/apps/core/wcm/components/page/v2/page/headlibs.html` 
has a reference to resource 
`cq/cloudconfig/components/scripttags/header`

> `<sly data-sly-resource="${'cloudconfig-header' @ resourceType='cq/cloudconfig/components/scripttags/header'}"></sly>`

However, I couldn't find it anywhere in crxde. Not sure if i'm missing anything here.

**Comment by hegarg** [comment]
Also, noticed under `/apps/core/wcm/components/page/v2/page/footer.html`, reference to a missing resource 
`<sly data-sly-resource="${'cloudconfig-footer' @ resourceType='cq/cloudconfig/components/scripttags/footer'}"></sly>`

**Comment by gabrielwalt** [comment]
Hi @hegarg, this is intended, and it allows your own page component that extends the core page component to specify these files in case you wish to inject additional code in your page header or footer.

We might need to better document this extension point.

**Comment by gabrielwalt** [comment]
We might need to document this better.

**Comment by vladbailescu** [comment]
@hegarg, Thanks for raising this issue, the errors slipped through our checks.

The two included resource types were added to support integration with Adobe Launch: (see https://helpx.adobe.com/experience-manager/kt/integration/using/adobe-launch-integration-tutorial-understand.html and https://marketing.adobe.com/resources/help/en_US/dtm/faq-launch.html) in the next AEM release.

Unfortunately these were not backported to 6.3 so we will need to conditionally include them to avoid these errors.
