### ISSUE TITLE
Add package.json to repository

### ISSUE THREAD

**Issue by janrembold** [Adobe-Marketing-Cloud/aem-core-wcm-components#122]
Please add valid package.json file to enable loading of this repository by npm/yarn

**Comment by gabrielwalt** [comment]
Hi @janrembold, supporting NPM isn't the main focus for now, therefore closing this for now.
However, feel free to submit a pull-request if desired.

**Comment by jckautzmann** [comment]
FYI: we now have a package.json at:
https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/master/content/package.json
