### ISSUE TITLE
Core Components 2.0.2 no longer compatible with AEM 6.3

### ISSUE THREAD

**Issue by stefanseifert** [Adobe-Marketing-Cloud/aem-core-wcm-components#124]
the new release 2.0.2 of core components is no longer compatible with AEM 6.3 - is this by design? 
#114 breaks compatibility - there is no resource type {{wcm/foundation/components/basicpage/v1/basicpage}} in AEM 6.3 + SP1 + FP20593.

only supporting AEM 6.4 for all releases > 2.0.0 is a but unfortunate because then also bugfixes and other improvements cannot be used for AEM 6.3 projects.

please also update the system requirements table on the main README.

**Comment by bpauli** [comment]
@stefanseifert The FP for AEM 6.3 with the basicpage component will be released shortly. But thank you for the pointer. We will flag the 2.0.2 release as a prerelease as long as the FP is not public available.

**Comment by kwin** [comment]
@bpauli Can you please extend the System Requirements on the readme.md (https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components#system-requirements) in this regard?
