### ISSUE TITLE
Eclipse IDE Maven issue when importing project

### ISSUE THREAD

**Issue by kmordan24** [Adobe-Marketing-Cloud/aem-core-wcm-components#125]
Issue: Eclipse is unable to update Maven Project for core.wcm.components.sandbox.bundle
![image](https://user-images.githubusercontent.com/20425837/37002160-04424430-2086-11e8-8e6a-c488a60193ee.png)

System Info: Eclipse Oxygen.2, AEM Developer Tools for Eclipse 1.1.0, Maven 3.3.9, Java 8

"Solution": Remove "\<execution>" section from maven-bundle-plugin in pom.xml

**Comment by kwin** [comment]
This is a problem with AEM Developer Tools and not with this project. It is already fixed in the latest Sling IDE Tools.

**Comment by kmordan24** [comment]
@kwin You are correct. Actually it looks like it will be fixed with Maven Archetype 12: https://github.com/Adobe-Marketing-Cloud/aem-eclipse-developer-tools/issues/78

I'll close this.
