### ISSUE TITLE
Breadcrumb component misses schema.org microdata

### ISSUE THREAD

**Issue by janrembold** [Adobe-Marketing-Cloud/aem-core-wcm-components#129]
The Breadcrumb component misses schema org microdata that is relevant for SEO.

I added microdata to Breadcrumb  according to http://schema.org/BreadcrumbList - see PR https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/pull/128 here

**Comment by vladbailescu** [comment]
Thanks for the proposal Jan, this is an interesting idea and we will take into consideration adding microdata to all components where this makes sense.

**Comment by gabrielwalt** [comment]
+1, I like the idea very much.

**Comment by vladbailescu** [comment]
We should actually review http://schema.org/docs/full.html and see if it makes sense to add microdata for other components as well

**Comment by bpauli** [comment]
fixed with https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/commit/fae1a0d4ef347cd3f3afde94c934209ccc048b91
