### ISSUE TITLE
Core WCM Components Core Bundle v2.0.4 is in installed state.

### ISSUE THREAD

**Issue by raghava-joijode** [Adobe-Marketing-Cloud/aem-core-wcm-components#146]
Core WCM Components Core Bundle is in installed state, when created new project using archetype 13 and deployed.

**My Product Info:**
License
  Customer: Raghava Joijode
  Download ID: 2ded2946-598e-5f4b-b5ef-ef1c3c68c271
  Product : Adobe Experience Manager (6.3.0)

Installed Products
  Adobe Experience Manager (6.3.1.0)
![capture-bundle-error](https://user-images.githubusercontent.com/26365498/38174511-dd7aa7fe-35eb-11e8-9927-c69ada99485d.PNG)
![capture-productinfo](https://user-images.githubusercontent.com/26365498/38174512-ddaf68b8-35eb-11e8-8e0e-b29ead176985.PNG)

**Comment by justinedelson** [comment]
Do you have CFP2 and Feature Packs FP20593 + FP20696 installed? Per https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/master/README.md#system-requirements, these are required dependencies for 2.0.4.

**Comment by raghava-joijode** [comment]
Apologies, I didnt had "CFP2 and Feature Packs FP20593 + FP20696". After installing bundle got resolved and is active.
