### ISSUE TITLE
Feature request: Video component

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Marketing-Cloud/aem-core-wcm-components#148]
Just like we have the Image-component, it would be nice to have a Video-component. This component should work the same way the Image-component does: You either specify a video asset, or you upload a video directly.

**Comment by richardhand** [comment]
Thanks @henrykuijpers for the suggestion, a new video component is on our roadmap (https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/wiki).

**Comment by kwin** [comment]
Isn’t this a duplicate of #218?

**Comment by jckautzmann** [comment]
@kwin You're correct. I'm closing this issue. Let's continue the discussion on #218.

**Comment by gabrielwalt** [comment]
Note that for now, the RTC on #218 doesn't allow direct upload on the component, and only referencing a video from DAM. The reason for this is that there probably needs to be a workflow triggered when uploading a video to generate the different encodings that might be needed.
