### ISSUE TITLE
[Maven] Update AEM uber-jar dependency

### ISSUE THREAD

**Issue by vladbailescu** [Adobe-Marketing-Cloud/aem-core-wcm-components#152]
Since AEM 6.4 is now available, we should update our uber-jar depedency

**Comment by kwin** [comment]
Does this mean that from Version 2.0.6 on the core components will only be compatible with AEM 6.4? IMHO the dependency should always list the minimal version being supported and hopefully that will still be AEM 6.3 SP1 CFP2 even after the release of 6.4.

**Comment by bpauli** [comment]
The minimum AEM version for the 2.0.6 release will AEM 6.3 with SP 2 installed.

Updated dependency in 1f42b61872c0256119e3776b9a0e36e3c58a221e

**Comment by bpauli** [comment]
fixed in ca4f0aed7572db7bc2aa3bebca6c09e4cf4683d6
