### ISSUE TITLE
[Image] editor" JS can throw error when overlaying the image component and hide checkbox isDecorative

### ISSUE THREAD

**Issue by patrickheinzelmann** [Adobe-Marketing-Cloud/aem-core-wcm-components#157]
If you overlay the image v2 component and hide the checkbox "isDecorative", a Javascript error is thrown:

Uncaught TypeError: Cannot read property 'querySelector' of undefined (editor.js:34)

Effected Version 2.0.4

**Comment by bpauli** [comment]
@patrickheinzelmann Can you please provide a content-package of the overlayed cq:dialog of your component? I was not able to reproduce the issue by only setting `sling:hideChildren` to `decorative` at the items node. Thanks!

**Comment by bpauli** [comment]
@patrickheinzelmann Can you please provide an update on this? Thanks!
