### ISSUE TITLE
[Maven] Overwrite full install directory with installation of core.wcm.components.all

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-core-wcm-components#159]
Currently `core.wcm.components.all` gets its full filter.xml automatically generated from the Maven Plugin. That leads to the fact that old bundle versions never get removed from the repository as the filter rule is only covering one specific bundle version, e.g. `/apps/core/wcm/install/core.wcm.components.core-1.0.6.jar`. Since the old bundle versions are not deployed anyways it would make sense to completely remove them from the repository by adding a filter rule for root `/apps/core/wcm/install`.

**Comment by bpauli** [comment]
@kwin Thank you very much for this useful hint!

**Comment by kwin** [comment]
There might be potential drawbacks (more theoretical though I think) with this change. For details please look at https://www.mail-archive.com/dev@jackrabbit.apache.org/msg40904.html.

**Comment by DominikSuess** [comment]
@kwin  - should https://github.com/apache/sling-org-apache-sling-installer-provider-jcr/blob/320079b499f88212faadf6eb0c7ef04978adb90d/src/main/java/org/apache/sling/installer/provider/jcr/impl/JcrInstaller.java#L137 take care of issues wrt install cycles? The CRX Packagemanager puts the JcrInstaller on hold until all resources are processed - so the events for resourcechanges are collected and added to the installer cycle together.
