### ISSUE TITLE
Unable to upload page thumbnail

### ISSUE THREAD

**Issue by bkowalk** [Adobe-Marketing-Cloud/aem-core-wcm-components#168]
Currently experiencing an issue after installing WCM core components 2.0.6, all pages have lost the ability to have an uploaded thumbnail in their page properties dialog - problematic for us since we're using those thumbnails in page content, not just for convenience inside the sites interface! Hoping someone can shed some light on if this is truly a bug, or if I've missed something in my steps below. 

Steps to reproduce:
- Run AEM 6.3 vanilla instance
- Install SP2 update
- Install we.retail 2.0.5 (latest release I can find that doesn't require AEM 6.4) (https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/releases/download/core.wcm.components.reactor-1.1.0/we.retail.all-2.0.5-SNAPSHOT.zip)
- Install core components 2.0.0
- Restart AEM to make sure all clientlibs are freshly generated

- In Incognito to avoid cached clientlibs, go to any page in the we.retail tree, click into edit mode (I used /content/we-retail/us/en/men)
- Click page properties in top left, go to thumbnail tab. 
- Click chain icon to break inheritance and allow upload. Upload an image. Should work and save properly.

- Now, install core components 2.0.6. (or 2.0.4 - effect should be the same)
- Retry image thumbnail upload. Upload should fail. No console messages, no network traffic. No change to thumbnail.  

Is anyone else experiencing the same issue?

Thanks!

**Comment by bkowalk** [comment]
After further exploration, I believe the issue has been found to be the removal of /apps/core/wcm/components/page/v1/page/clientlibs/editor/js/pagethumbnail.js. This, along with other dialog items, have been removed in order to rely on the built-in "basicpage" component.

However, Adobe's own /libs/cq/gui/components/common/wcm/clientlibs/wcm/js/pagethumbnail.js is out of date and doesn't work with the latest core components, causing all image uploads in the page properties dialog to fail.

Duct tape fix on my instance: I've brought back the removed core pagethumbnail.js and am overriding it onto core components 2.0.6.

Recommended fix: Adobe should update their pagethumbnail.js, and Core components should keep the JS file in place until this update is made.

Thanks!

**Comment by bpauli** [comment]
@bkowalk, thank you for reporting this issue! I was able to reproduce this issue and we will discuss how to provide a fix for this issue.

**Comment by bpauli** [comment]
@bkowalk, we included a fix for this issue for the upcoming SP3 for AEM 6.3.

For the time the SP in not released, a valid workaround would be to add the the pagethumbnail.js from [1] again in the proxy component on project level.

Thanks again for bringing this issue up!

[1] https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/core.wcm.components.reactor-2.0.0/content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/clientlibs/editor/js/pagethumbnail.js
