### ISSUE TITLE
Support picture element for the image component

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-core-wcm-components#17]
Currently the image component is relying on a lot of javascript for the adaptive image rendering. At least optionally the image component should give out picture elements (https://developer.mozilla.org/en/docs/Web/HTML/Element/picture) instead. The browser support is meanwhile pretty good.

**Comment by gabrielwalt** [comment]
The issue with the picture element is that it allows only to query the viewport width and not the element width, which is pointless in our case: we need to know how wide the image element is to be able to know what is the optimal size to load.

**Comment by raducotescu** [comment]
In addition to what @gabrielwalt has commented, `<picture>` is not supported in IE and the current available polyfills don't seem to bring proper support for it. Furthermore, we still need to be able to cleanly support browsers where JavaScript is turned off.
