### ISSUE TITLE
[Image] Add support for SVG images

### ISSUE THREAD

**Issue by jckautzmann** [Adobe-Marketing-Cloud/aem-core-wcm-components#170]
The Core Image Component should be enhanced to allow SVG images to be used with it.

**Comment by kwin** [comment]
I don’t think it’s wise to support rasterized and vector-based images with the same component, as they differ a lot in terms of editing options (cropping, resizing, ...). Please rather support SVG through a dedicated component

**Comment by gknobloch** [comment]
The overall idea is to avoid creating a component for each and every thing. The end author excepts to be able to use an image, provide its image and then get the right options (vs. having to decide when dragging the component based on the image he'll pick).

Of course, there might be compromise required in some cases, we'll look into your feedback.

**Comment by gabrielwalt** [comment]
As @gknobloch said, our decisions of how to structure the components and the dialogs is driven by the authoring experience, so that the editing is as easy and efficient as possible.
But you're right @kwin, one challenge of the current approach will be to see whether we can remove the in-place image editor in case the image is a vector image as we won't support cropping, rotating or image maps on them.

**Comment by kwin** [comment]
One other important challenge is IMHO that the markup for SVG usually looks different.

**Comment by gabrielwalt** [comment]
@kwin: For now, we left the HTML markup roughly the same, mainly just referencing the SVG with an <img> element, but disabling the smart renditions for SVG files as we just stream the file, but don't want to resize or manipulate it. If we need to consider further use-cases or requirements, feel free to tell us about them. So far, it's a minimalistic SVG support, but it works and supporting more complex SVG embedding, like inlining it into the HTML, opens a pandora box of security concerns.

**Comment by andreeadracea** [comment]
Solved this in 561a45c7d8826ea4fa37392f03efbaf30d7b2b8b commit
