### ISSUE TITLE
Navigation component: NPE when any page has special redirect target

### ISSUE THREAD

**Issue by joaotab** [Adobe-Marketing-Cloud/aem-core-wcm-components#174]
When using the redirect target in the page component to redirect to an external page or to an internal page with additional selectors a NullPointerException is generated here on the NavigationImpl class:

`private boolean currentPageIsRedirectTarget(Page page) {`
[...]
`Page redirectPage = pageManager.getPage(redirectTarget);`
**-->**` if (redirectPage.equals(this.currentPage)) {` **<--**

Maybe the logic should be reversed (e.g. this.currentPage.equals...) to avoid crashing the component in these scenarios?

**Comment by msagolj** [comment]
supplied fix and test for it.

**Comment by vladbailescu** [comment]
@msagolj, please also cherry-pick the fix to `master` branch!
