### ISSUE TITLE
Image: Document under which circumstances which image URL is requested from the server

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-core-wcm-components#18]
Obviously the image components supports different server-side generated renditions of the same image. It is not clear to me though from the documentation when which size is being requested from the client.
I tried to resize my browser window below one of the allowed width and still the image is requested with the selector for the largest allowed width, so there must be some other criteria which determine which rendition is requested (except for the width of the browser window). Please outline which criteria that is (and how to influence that, if possible).

**Comment by gabrielwalt** [comment]
+1 we need to better document this.

The image component will never load a smaller image size if it initially requested a bigger image. But if you reload the page while being very narrow and then resize it to be wider, it will load the larger allowed size when needed, based on the element size and pixel density of the display.

**Comment by kwin** [comment]
@gabrielwalt Thanks for the input. But with my retina display I couldn't bring it to load a 500px version of it, even if the screen width is very narrow initially (far below 500px according to the device emulator). So how does the pixel density is taken into account? Is the lower version only being loaded in case the screen width is really below the real 500 pixels (and not the calculated pixel size considering the DPI configuration)?

**Comment by gabrielwalt** [comment]
@kwin Do you have a policy configured? In the template editor, or design mode, you need to configure the image component and provide the list of allowed sizes. When none is configured, it disables smart image loading and loads the image in 1280px wide. When one is configured, the `img` element is then wrapped in a `noscript` element and the corresponding JS script is needed to properly load the image.

**Comment by kwin** [comment]
After a 2nd try it really worked. It is just confusing that the device emulators shows the CSS pixels and not the real pixels. If you reduce your width to real 500pixels the smaller rendition is being requested correctly. Maybe it would be worth to indicate a hint in the device emulator about the real pixels as well.

**Comment by gabrielwalt** [comment]
Hm, good point. I'm not sure that we should change the device emulator though, but maybe adding a note in the policy dialog of the image component would help: under the allowed components, tell that these are device pixels and not CSS pixels.

**Comment by raducotescu** [comment]
Also, @gabrielwalt this statement is not true:

> The image component will never load a smaller image size if it initially requested a bigger image.

In the current implementation the client will actually request a smaller image to be loaded if you reduce the image container's width.

**Comment by raducotescu** [comment]
@kwin, do you need more info here? In then end it seems you had a problem with the device emulator and not with the image component. :)

**Comment by kwin** [comment]
It would still be good to have the URL format documented (to allow to whitelist that in the HTTPD/Dispatcher accordingly and to also set the caching headers accordingly) and in addition define which server-side rendition is requested for which container width.

**Comment by raducotescu** [comment]
@kwin, we can definitely add the URL format in the README of the Image component - I'll create an issue for this.

Regarding the server-side renditions, this is actually handled by the content policy you define for the image component + the size of container width, which is client-side specific. The only piece of info that we could document is that we pick the rendition that either has a width equal to the container width, or the immediately wider one.

**Comment by kwin** [comment]
Yes, exactly. Those two points were really helpful.

**Comment by bpauli** [comment]
@kwin As the documentation task is handled in #28 can we close this issue?

**Comment by kwin** [comment]
Yes, I am closing this issue.
