### ISSUE TITLE
ImageImpl v2 - Make proper use of the Sling Delegation Pattern

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Marketing-Cloud/aem-core-wcm-components#180]
https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/e0ad89c967cbfc098624a2d4f54d8494e4916658/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/ImageImpl.java

This impl class is extending another impl class, but we can now prevent this with Sling Delegation.

**Comment by vladbailescu** [comment]
Thanks for the suggestion but this a pattern that is appropriately used when extending the implementation is not possible (ie: from a different bundle). There's no need to do that here.
