### ISSUE TITLE
List Component Pagination

### ISSUE THREAD

**Issue by scottk0000** [Adobe-Marketing-Cloud/aem-core-wcm-components#182]
The documentation says the List Compnent provides: Ordering, pagination and limit.  I see both Ordering and Limit, but I do not see a way to set Pagination.  Is the Pagination feature implemented?

**Comment by richardhand** [comment]
hi @scottk0000 - thanks for the question! There is currently no pagination feature for the list component. We've updated the documentation to reflect that in https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/commit/c9b786e5a6a34829ac42b3b98725cafdf8b18ae5

**Comment by richardhand** [comment]
@scottk0000 - sure! Just create a new issue with the requested feature and we will review whether we want to introduce it. Try to provide as much detail as possible about what you expect from the feature.

I will close this issue.

**Comment by Sanjana523** [comment]
I am facing an issue. I have copied the pagination node and other required files from the foundation folder and it's working fine when I'm not using the core component client libraries. Please help me
