### ISSUE TITLE
[Image] Disable IPE toolbar items for certain mime types

### ISSUE THREAD

**Issue by bpauli** [Adobe-Marketing-Cloud/aem-core-wcm-components#193]
After the added support for SVG images in the core components image component (#171) we have to find a way to disable toolbar items of the IPE (Inplace Editor) which are currently not supported for certain mime types. For example cropping of an SVG image is currently not possible and should therefore not be provided in the IPE.

Note: This config option will only be taken into consideration after a new feature pack is available and is installed on top of AEM 6.4.

**Comment by kwin** [comment]
Since this has been merged, can you clarify which featurepack/sp level is necessary for this to be effective?

**Comment by gabrielwalt** [comment]
* For 6.3, it's FP 24268:
https://www.adobeaemcloud.com/content/marketplace/marketplaceProxy.html?packagePath=/content/companies/public/adobe/packages/cq630/featurepack/cq-6.3.0-featurepack-24268
* For 6.4, it's FP 24267:
https://www.adobeaemcloud.com/content/marketplace/marketplaceProxy.html?packagePath=/content/companies/public/adobe/packages/cq640/featurepack/cq-6.4.0-featurepack-24267
Both just got published.
