### ISSUE TITLE
[Image] Document the SVG behavior

### ISSUE THREAD

**Issue by richardhand** [Adobe-Marketing-Cloud/aem-core-wcm-components#199]
We should document the SVG support that was recently added to the image component in https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/pull/171, to describe its behavior in relation to adaptive image widths.

**Comment by gabrielwalt** [comment]
(CQ-4247325)

**Comment by andreeadracea** [comment]
Soved this in 76b8259bdf2a17fa4c55112c5e066480d508ee10 commit
