### ISSUE TITLE
cq-wcm-sightly-extension dependency not available 

### ISSUE THREAD

**Issue by etherel** [Adobe-Marketing-Cloud/aem-core-wcm-components#2]
<dependency>
            <groupId>com.adobe.cq.sightly</groupId>
            <artifactId>cq-wcm-sightly-extension</artifactId>
            <version>1.3.4</version>
            <scope>provided</scope>
        </dependency>

In commons-testing/pom.xml can not be resolved

https://repo.adobe.com/nexus/content/repositories/public/com/adobe/cq/

**Comment by etherel** [comment]
Other problems exist with the dependencies meant to be in the repo, the versions of:
- cq-search
- cq-tagging 
are not present.

**Comment by justinedelson** [comment]
@gabrielwalt @raducotescu shouldn't this project depend upon the uberjar?

**Comment by etherel** [comment]
@justinedelson thanks for forwarding this on.  The uber.jar is a dependency in many places e.g. see commons-testing:

     ```
   <dependency>
            <groupId>com.adobe.cq.sightly</groupId>
            <artifactId>cq-wcm-sightly-extension</artifactId>
            <version>1.3.4</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.adobe.aem</groupId>
            <artifactId>uber-jar</artifactId>
            <classifier>obfuscated-apis</classifier>
            <scope>provided</scope>
        </dependency>
```

**Comment by raducotescu** [comment]
Those artifacts, which unfortunately don't seem to be deployed to the Adobe public repo, are needed for correctly running the unit tests for the Sightly use objects. Due to how the uber jar was built, API classes seem to have a default constructor generated that does nothing, with the same signature as the original constructor.

**Comment by justinedelson** [comment]
Right, I meant the unobsfucated version.

**Comment by etherel** [comment]
@raducotescu can't you deploy the missing artefacts to the public repo?
