### ISSUE TITLE
[Form Container] - Component Not Rendering & Throwing Error

### ISSUE THREAD

**Issue by brandonmaynard** [Adobe-Marketing-Cloud/aem-core-wcm-components#209]
## Bug Report

**Current Behavior**
When dropping the Form Container on a parsys, nothing renders and the following error is present in the logs:
`08.06.2018 16:03:05.043 *ERROR* [0:0:0:0:0:0:0:1 [1528491784823] GET /content/path/to/page/my-page.html HTTP/1.1] org.apache.sling.servlets.get.impl.DefaultGetServlet No renderer for extension html, cannot render resource TypeOverwritingResourceWrapper, type=my-project/components/content/form/container/new, path=/content/path/to/page/my-page/jcr:content/main-par/container/*, resource=[StarResource, type=sling:syntheticStarResource, path=/content/path/to/page/my-page/jcr:content/main-par/container/*]`

**Expected behavior/code**
The component should be available for me to author

**Environment**
- AEM version 6.3.2
- Core Components version 2.0.6
- JRE version Java(TM) SE Runtime Environment (build 1.8.0_161-b12)

**Possible Solution**
N/A

**Additional context / Screenshots**
I tried to add this component with WeRetail's Form Container as well and I got the same error.
Here is how my component is set up:
`<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0"
jcr:primaryType="cq:Component"
jcr:title="Form Container"
sling:resourceSuperType="core/wcm/components/form/container/v2/container"
componentGroup="My Group"/>`

**Comment by msagolj** [comment]
Hi @brandonmaynard 
Couldn't reproduce your issue. What i did:
- aem 6.3.2.0, 
- core components 2.0.6,
- we.retail 2.0.4 (needed with core comp 2.0.6)
 https://github.com/Adobe-Marketing-Cloud/aem-sample-we-retail/releases/tag/we.retail-2.0.4

I tried the we.retail form container(v1), core form container(v2) and a proxy form container(v2) on we.retail pages and on a new empty template i created. all worked.

your proxy component seems to be missing the cq:isContainer = true property, but i'm not sure its the reason for your issue. Did you use we.retail 2.0.4 ?

**Comment by brandonmaynard** [comment]
Thank you @msagolj, `cq:isContainer="{Boolean}true"` missing from the `.content.xml` file was the issue. I am closing this.

**Comment by Jaydipatel** [comment]
We are still facing this issue on AEM 6.5.18
