### ISSUE TITLE
Potential unclosed resources in AdaptiveImageServlet

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Marketing-Cloud/aem-core-wcm-components#21]
https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/da012e690e33d33051df268233eb92f5d0e11423/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java

Several times IOUtils.closeQuietly() is used outside a finally block, so it could be possible that inputstreams are not closed.

**Comment by bpauli** [comment]
@henrykuijpers, Thanks for reporting this issue!
