### ISSUE TITLE
[Page] Get rid of the icon.png file

### ISSUE THREAD

**Issue by jckautzmann** [Adobe-Marketing-Cloud/aem-core-wcm-components#215]
We should get rid of the icon.png file in content/src/content/jcr_root/apps/core/wcm/components/page/v2/page/icon.png as it is not used in the code.

**Comment by gabrielwalt** [comment]
(CQ-4247321)

**Comment by andreeadracea** [comment]
Solved in 0e85cf0dd61c3fd100eadddae26e52adf5518deb commit
