### ISSUE TITLE
Image component displays title only if isDisplayTitlePopup is false

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Marketing-Cloud/aem-core-wcm-components#22]
https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/image/v1/image/image.html

    <span class="cmp-image--title" data-sly-test="${!image.displayPopupTitle && image.title}">${image.title}</span>

This should obviously be: 

    <span class="cmp-image--title" data-sly-test="${image.displayPopupTitle && image.title}">${image.title}</span>

**Comment by raducotescu** [comment]
This is not a bug. As you've mentioned in #23, you have the option to check the "Display caption as pop-up" option in the edit dialog. The info pop-up provides the following details:

> When checked, the caption won't be displayed below the image, but as a pop-up displayed by some browsers when hovering over the image.
