### ISSUE TITLE
[Carousel] Create carousel dialog iteration 1

### ISSUE THREAD

**Issue by richardhand** [Adobe-Marketing-Cloud/aem-core-wcm-components#235]
As an author, I need a dialog to reorder and delete my slides, and manage their titles.

* Editable, editing the component's title.
* Possibility to delete the slide.
* Nesting is not looked up, in case a child component has a title, that would be ignored.
* If no title is found (or if it is not on the direct slide component), a default title is displayed as a placeholder (eg. Slide #1).
* Display the Style tab...
* No component reordering for now.
* No add button for now.

(CQ-4247667)

**Comment by richardhand** [comment]
This enhancement is available in the [2.2.0 release](https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.2.0) as part of the new Carousel Core Component.

**Comment by magento-engcom-team** [comment]
:x: Cannot export the issue. GitHub repo adobe/aem-core-wcm-components is not supported in JIRA project undefined and type undefined.

**Comment by magento-engcom-team** [comment]
:x: Cannot export the issue. GitHub repo adobe/aem-core-wcm-components is not supported in JIRA project undefined and type undefined.

**Comment by magento-engcom-team** [comment]
:x: You don't have the permission to export this issue.

**Comment by magento-engcom-team** [comment]
:x: You don't have the permission to export this issue.
