### ISSUE TITLE
[FormHidden] Display field name and value on placeholder

### ISSUE THREAD

**Issue by brandonmaynard** [Adobe-Marketing-Cloud/aem-core-wcm-components#240]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When using multiple Form Hidden Components, there is no way to tell how each one is configured without opening/closing each dialog. We need a way for authors to be able to tell what each Form Hidden Component's configured values are easily.
**Before:**
![image](https://user-images.githubusercontent.com/32407610/42358459-5d8a9d18-80a2-11e8-8120-6f7dae75e7e5.png)
**After:**
![image](https://user-images.githubusercontent.com/32407610/42358467-68325580-80a2-11e8-9935-4218c5c9ba7d.png)

**Describe the solution you'd like**
Pull Request will be opened with the solution for both v1 and v2 versions

**Are there alternatives?**
N/A

**Documentation**
N/A - Only a change to the UI in edit mode

**Comment by gabrielwalt** [comment]
I like this enhancement very much, thank you again, @brandonmaynard!
