### ISSUE TITLE
Add System Requirements in Readme for Release 2.1.0

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-core-wcm-components#245]
## Feature Request

Please list the necessary Feature Packs for version 2.1.0 in the System Requirements table in the readme (https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/master/README.md#system-requirements)

**Comment by vladbailescu** [comment]
Thanks @kwin! This was on our TODO list before marking the release public, will probably happen today, after all checks are completed.

**Comment by vladbailescu** [comment]
Fixed by https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/commit/0cb1a0481272c18fe28c376f3a96dbb70786a979
