### ISSUE TITLE
[Teaser] - Action Links Don't Work/Save

### ISSUE THREAD

**Issue by brandonmaynard** [Adobe-Marketing-Cloud/aem-core-wcm-components#253]
## Bug Report

**Current Behavior**
Call to Action links render without an href and the 'link' value does not save in the JCR

**Expected behavior/code**
Value should be saved in the JCR and the href should be populated in the markup

**Environment**
- AEM version - 6.3.2.2
- Core Components version - 2.1.0
- JRE version - 1.8.0_152-b16

**Possible Solution**
N/A

**Additional context / Screenshots**
![image](https://user-images.githubusercontent.com/32407610/43433427-dd9a86aa-943c-11e8-999e-eb0f46b63417.png)

**Comment by vladbailescu** [comment]
@brandonmaynard, thanks for reporting this issue. We also discovered this with 6.3.2.2 and the issue was logged internally as GRANITE-22267. This is going to be fixed in 6.3.3.0
