### ISSUE TITLE
Allow to configure image quality in AdaptiveImageServlet

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-core-wcm-components#254]
## Feature Request

Allow to configure the quality value of the generated image binary from the AdaptiveImageServlet via content policies .

Currently only 1.0f is being hardcoded as 2nd parameter in https://helpx.adobe.com/experience-manager/6-2/sites/developing/using/reference-materials/javadoc/com/day/image/Layer.html#write(java.lang.String,%20double,%20java.io.OutputStream) in the AdaptiveImageServlet (https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/54f5c002db11f34f9561a5eff09afa3af05741d9/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/AdaptiveImageServlet.java#L365)
This leads to 100% quality (and therefore bigger file sizes for JPEG). In some cases it would be desirable to render with a different quality value.

**Comment by bpauli** [comment]
Hi @kwin,

Thank you for creating this useful feature request. We will discuss it shortly and keep you updated.

CQ-4249803

**Comment by kwin** [comment]
Most probably it will be even more useful to define different quality factors per size and mimetype.

**Comment by kwin** [comment]
Just to stress how important this is I tried it out with the image from https://privatschutz.allianz.de/out/dwAllianzPrivat/img/background/startpage_full.jpg.

When delivering this with quality 1.0 with a width of 2048 pixels I end up with a size of 1.3 MB.
When reducing the quality factor to 0.8 with a width of 2048 pixels I end up with a size of 346 KB. With a factor 0.8 I can not see any noticeable quality difference and this ends up with a size of only 25%(!) compared to the one rendered with a quality of 1.0.

So even the default within Core WCM Components should not be 1.0 but rather much less.

**Comment by kwin** [comment]
One more related issue is with GIFs, due to the hardcoding of the 1.0 the number of colors is being reduced to 2 (within `com.day.image.ImageSupport#doCreateGIFMetadata(...)`).

**Comment by kwin** [comment]
As long as only JPEG is supported (GIF is never transformed and all other image types disregard the quality being given) it is most probably enough to configure it only once.
