### ISSUE TITLE
Example for component change from v1 to v2, how does it impact package release version

### ISSUE THREAD

**Issue by lbaoyu** [Adobe-Marketing-Cloud/aem-core-wcm-components#26]
Is there an example explains when a core component's version should change from v1 to v2, and in that case how the package version number increase?

**Comment by raducotescu** [comment]
@lbaoyu, have you had a chance to read the info from https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/wiki/AEM-Core-WCM-Components'-versioning-policies? If that doesn't answer your question, please feel free to re-open / clone this issue.
