### ISSUE TITLE
[Image] Image component not working with more than one "Widths" added

### ISSUE THREAD

**Issue by MrPoofy** [Adobe-Marketing-Cloud/aem-core-wcm-components#260]
Hi!

I'm trying to use the **Image** component and it's working fine, but when i add more than one pixel value to the "Widths" multi-field

![image](https://user-images.githubusercontent.com/645789/43772479-2fea1a8a-9a3a-11e8-8c04-ac6f12f7d452.png)

The component stops working and no image is visible. I'm using the last version of the core components on a AEM 6.4 environment. I have embebed the "core.wcm.components.image.v2" on my clientlibs. I'm installing the common components using my pom:

![image](https://user-images.githubusercontent.com/645789/43772761-16e7b3f2-9a3b-11e8-896f-83302f802197.png)

And i created a proxy for the component on my components folder like so:

![image](https://user-images.githubusercontent.com/645789/43772624-9f6a09f6-9a3a-11e8-8826-14c585c1aa46.png)

Everything works fine, dialogs, options, etc.. only when i have more than one "Widths" configured it's when the image stops working.

**Comment by MrPoofy** [comment]
I'm closing the issue because i found the problem, i needed to create the **customfooterlibs** and **customheaderlibs** to load the clientlibs.

**Comment by cmariaxavier** [comment]
Hi @MrPoofy  
I am facing similar issue .Could you please help me out with this?
