### ISSUE TITLE
[CF]Content Fragment Error occured using core components 2.0.8+

### ISSUE THREAD

**Issue by hibiki-kamioka** [Adobe-Marketing-Cloud/aem-core-wcm-components#269]
## Bug Report

**Current Behavior**
When I used a content fragment component in we.retail page, include error of component was occured.
Please see the screenshots the below.

I could not find this issue using core components version 2.0.4, however I was able to find using 2.08+.

**Environment**
- AEM 6.4 SP1
- Core Components version (2.0.8, 2.1.0)
- JRE version (`Java(TM) SE Runtime Environment (build 1.8.0_162-b12)`)

**Additional context / Screenshots**
Screenshots(a)
![image](https://user-images.githubusercontent.com/42370761/44078433-6b4a0ec6-9fe1-11e8-9c55-97d98ed1c381.png)

Screenshots(b)
![image](https://user-images.githubusercontent.com/42370761/44078462-7fc7dcfc-9fe1-11e8-9f60-4fd888e437ba.png)

**Comment by bpauli** [comment]
@hibiki-kamioka, Please make sure that you also install the extension package after updating the core-components package. We always provide two packages for a release. The all package contains all components and the core bundle. The content fragment component is included in the extension package. Thanks!

**Comment by vladbailescu** [comment]
You can find the package on the release page you mentioned:

![core-components-extension](https://user-images.githubusercontent.com/3670963/44266744-5dc52380-a234-11e8-8074-6d013e304576.png)

**Comment by hibiki-kamioka** [comment]
@vladbailescu 

Sorry...
Thanks a lot.
