### ISSUE TITLE
[Tabs] Create a Tabs component

### ISSUE THREAD

**Issue by jckautzmann** [Adobe-Marketing-Cloud/aem-core-wcm-components#275]
As a page author, I want to structure content within tabs, so that I can structure the content displayed to the visitors into sections.

**Initial Requirements**

* As a page author, capability to add, remove, reorder containers
* As a page author, capability to switch to a specific container to edit its content
* As a page author, capability to edit the container title that is to be displayed in the Tab title
* The Tab should be one component with an edit config to switch between them
* In preview mode or on publish, capability to switch between the tabs

**Comment by jckautzmann** [comment]
The work is tracked in the following branch:
https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/tree/feature/tabs

**Comment by richardhand** [comment]
(CQ-4249922)

**Comment by richardhand** [comment]
This is available in the [2.2.0 release](https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.2.0) with the introduction of the new Tabs Core Component.
