### ISSUE TITLE
[Tabs] Nested tabs do not work

### ISSUE THREAD

**Issue by vladbailescu** [Adobe-Marketing-Cloud/aem-core-wcm-components#288]
We should make sure we can nest tabs and carousel components.

**Comment by richardhand** [comment]
This is available in the [2.2.0 release](https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.2.0) with the introduction of the new Tabs Core Component.
