### ISSUE TITLE
Major package version increase of model API packages in 1.0.5-SNAPSHOT

### ISSUE THREAD

**Issue by stefanseifert** [Adobe-Marketing-Cloud/aem-core-wcm-components#29]
In the master branch / 1.0.5-SNAPSHOT the major part of the package versions of the two API packages
```
com.adobe.cq.wcm.core.components.models
com.adobe.cq.wcm.core.components.models.form
```

breaking backward compatibility when deploying this new version to an instances with code compiled against 1.0.4. this is e.g. the case with AEM 6.3 and the included we.retail sample content - once 1.0.5-SNAPSHOT is deployed the bundle `com.adobe.cq.sample.we.retail.core` is stopped because it depends on `com.adobe.cq.wcm.core.components.models.form` v13.0.

was this done by intention? keep in mind that the interface are not only used by sightly templates, but by java code from other OSGi bundles as well. is it planned to publish multiple OSGi bundles with the latest and older implementations of the API packages which can be deployed in parallel?

**Comment by raducotescu** [comment]
The API versions had to be increases due to a bug in the 6.3 uber-jar that included the sample API and led to split packages warnings with the baseline plugin - see 922ed77. We.Retail will need to be recompiled agains this new version of the `aem-core-wcm-components` project.

**Comment by stefanseifert** [comment]
ok, thanks for the information
