### ISSUE TITLE
AEM Image Component does not load correct responsive image when used with OWL Image Slider

### ISSUE THREAD

**Issue by steffenhaak** [Adobe-Marketing-Cloud/aem-core-wcm-components#290]
## Bug Report

**Current Behavior**

- Use AEM Image Component in OWL Carousel Slider: http://owlcarousel2.github.io/OwlCarousel2/
- AEM image is responsive with different widths, lazy loading is disabled
- enable the following options in OWL Carousel:
`items: 1,
				nav: false,
				dots: true,
				navText: ['',''],
				margin: 30,
				loop: true,
				autoHeight: true,
				responsive : {
					768: {
						nav: true
					}
				}`
- Insert several AEM images
- Scroll back once in the slider; since looping is enabled the last image is displayed
- the image shown was cloned by OWL carousel. The image is displayed in the lowest possible resolutions, despite that being not optimal
- Resizing the window leads to the correct image resolution to be loaded, potentially because OWL carousel then performs some DOM mutations
- manually triggering the resize event (`window.dispatchEvent('resize')`) does not fix the problem.

**Expected behavior/code**
The images displayed when showing the cloned objects should have the correct optimal image resolution. 

**Environment**
- Core Components 2.0.8

**Possible Solution**
The mutation observer should detect the cloning of the AEM image component and initialize the image correctly.

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![image](https://user-images.githubusercontent.com/26477639/45699089-bbb59580-bb69-11e8-8456-317d6f9e129a.png)

![image](https://user-images.githubusercontent.com/26477639/45699189-dab42780-bb69-11e8-9955-a022adb51cbe.png)
![image](https://user-images.githubusercontent.com/26477639/45699268-f15a7e80-bb69-11e8-969f-0cc13889bcba.png)

**Comment by jckautzmann** [comment]
@steffenhaak Thx for reporting this issue. We will have a look at it and prioritize it. If you know how it could be fixed, you’re welcome to submit a pull request and we’ll have a look at it.
Please note that we are working on a Carousel component [0] in the `development` branch, which you might want to use instead of the OWL one.

[0] https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/tree/development/content/src/content/jcr_root/apps/core/wcm/sandbox/components/carousel/v1/carousel

**Comment by jckautzmann** [comment]
(CQ-4253296)

**Comment by vladbailescu** [comment]
Should be fixed by #306

**Comment by steffenhaak** [comment]
@vladbailescu Thank you very much for the fix and sorry (!) for the late response. I was out of office for quite some time. I will integrate the fixed version within the next days and then give feedback if it solved the issue in our project.
