### ISSUE TITLE
Support version diffing

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-core-wcm-components#3]
Currently all new component don't support the version diffing being described in https://docs.adobe.com/docs/en/aem/6-2/author/page-authoring/working-with-page-versions.html#Comparing%20with%20a%20Previous%20Version%20-%20Touch%20UI. Are there any plans on supporting that feature which is in my opinion pretty crucial for bigger sites (e.g. for doing reviews).

**Comment by gknob** [comment]
@kwin we're working on supporting this in Touch UI by doing client-side diff (to avoid every component to have to implement the diff service at every component level, like it was in Classic UI.

This is one of the top priority 6.3 feature, and we're also working on a 6.2 backport.

Based on this information, I think this issue should be closed.

**Comment by kwin** [comment]
@gknob Thanks a lot for that update. Even better then.
