### ISSUE TITLE
[Carousel][Image] Images don't get the proper size/width when they are selected into the view

### ISSUE THREAD

**Issue by vladbailescu** [Adobe-Marketing-Cloud/aem-core-wcm-components#305]
Steps to reproduce:

Add a carousel to the page
Add two image components and configure the images
Switch the active slide
Expected result: the image that appears has the proper resolution/width

Actual results: the image that appears has the lowest resolution/width

**Comment by vladbailescu** [comment]
CQ-4254130

**Comment by kwin** [comment]
Is this also solving #290?

**Comment by vladbailescu** [comment]
It should AFAICT. @steffenhaak, could you please check?

**Comment by vladbailescu** [comment]
I took some time to setup an _owlcarousel_ and it works ok with the proposed patch:

![owl-carousel](https://user-images.githubusercontent.com/3670963/46467799-5e5f4c80-c7d7-11e8-982b-4ec82c455384.gif)
