### ISSUE TITLE
[Tabs] Allow authors to specify a default selected item

### ISSUE THREAD

**Issue by vladbailescu** [Adobe-Marketing-Cloud/aem-core-wcm-components#316]
As an author I would like to specify which tab is selected by default

**Comment by vladbailescu** [comment]
CQ-4254373

**Comment by richardhand** [comment]
This enhancement is available in the [2.2.0 release](https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.2.0) with the introduction of the new Tabs Core Component.
