### ISSUE TITLE
Document javascript logic and necessary markup for the image component

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-core-wcm-components#33]
As the image component relies on some javascript to dynamically modify the DOM (to request the most appropriate image renditions) the necessary markup attributes for this javascript logic should be documented. This is especially important as otherwise extending from this component may easily lead to wrongly placed markup (compare with https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/issues/30#issuecomment-309422119)

**Comment by dixit4patel** [comment]
@raducotescu  / @kwin  Can you please explain a bit more? I am using core image component and getting https://forums.adobe.com/thread/2352665 issue. Only after removing "<noscript data-sly-unwrap="${!image.json}" data-cmp-image="${image.json}">" line in image.html, image gets displayed. But then the images are not responsive based on screen size. I have provided "smartImages" and "smartSizes" in Design dialog. Not sure whats breaking.
