### ISSUE TITLE
Search Core Component Doesn't Work With Query Parameter

### ISSUE THREAD

**Issue by vivekdhiman** [Adobe-Marketing-Cloud/aem-core-wcm-components#332]
Hi,

I was looking over the search component functionality. I found a change in behavior between **/apps/core/wcm/components/search/v1/search** and **/libs/foundation/components/search** components. 

When I hit page with query parameter with ?q=value parameter. Legacy component take this as input value and render the results.

However, In core component this behavior is miss. Is that a bug or core search component does not adhere this functionality?

Thanks

**Comment by bpauli** [comment]
@vivekdhiman The search component of the core-component is not compatible with the legacy foundation search as it was designed with an Ajax approach.
