### ISSUE TITLE
[Carousel][Tabs] The Add button in the edit dialog for Carousel/Tabs does not work

### ISSUE THREAD

**Issue by awudome** [Adobe-Marketing-Cloud/aem-core-wcm-components#341]
## Bug Report

**Current Behavior**
I have a fresh install of AEM 6.4.2.0 + Core components 2.2.0 with 2 new custom components proxied with sling:resourceSuperType to v1 of the carousel and tabs components. The 2 new components have been enabled for use via layout component policy.

The add button in the edit dialog does nothing when I click on it. A Javascript error is thrown in the browser console. The error is the same for both carousel and tabs . See screenshot.

**Expected behavior/code**
I was expecting the add button to yield a textfield each time you click on it.

**Environment**
- AEM 6.4 (6.4.2.0)
- Core Components version 2.2.0
- JRE version: Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
- Google Chrome incognito mode Version 69.0.3497.100 (Official Build) (64-bit)

**Possible Solution**
N/A

**Additional context / Screenshots**
![tabs-screenshot](https://user-images.githubusercontent.com/22158736/47307504-c9d95480-d5f4-11e8-9628-e5666d416d43.png)

**Comment by msagolj** [comment]
Hi,

Did you set the `./cq:isContainer` property on the proxy as described [here ](https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel#enabling-carousel-editing-functionality) ?

**Comment by DriesVanbilloen** [comment]
Hi,
I have the same issues with these components and I'm really excited to work with them. I've made a print screen for my configuration: 
![screen shot 2018-10-23 at 15 00 58](https://user-images.githubusercontent.com/16015343/47362341-7dfddc80-d6d4-11e8-8e20-36a1d1b93322.png)

**Comment by DriesVanbilloen** [comment]
> Hi,
> I have the same issues with these components and I'm really excited to work with them. I've made a print screen for my configuration:
> ![screen shot 2018-10-23 at 15 00 58](https://user-images.githubusercontent.com/16015343/47362341-7dfddc80-d6d4-11e8-8e20-36a1d1b93322.png)

I've fixed it by adding the properties of the cq:editConfig directly into the self made component (see image).
This issues can be closed!

**Comment by awudome** [comment]
Works for me after setting ./cq:isContainer. Closing the issue.

**Comment by A30001046** [comment]
./cq:isContainer is really not resolving the issue.
Can someone please provide correct solution for this simple tab core component?

**Comment by richardhand** [comment]
@A30001046 - please create a new issue explaining the problems you are still having including steps to replicate and the environment you are testing with. The retested the recommended fixes here and they work for the environment listed.

Also consider upgrading to [Core Components 2.2.2](https://github.com/adobe/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.2.2) or higher if you are still on 2.2.0 - it contained a number of important fixes for the Tabs and Carousel components.

**Comment by A30001046** [comment]
Hi @richardhand ,
Thanks for response and we managed to get it work with correct core component structure.
Thanks!
