### ISSUE TITLE
[Image] Image map not supported

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-core-wcm-components#35]
Although the inplace editor of the image component does allow to maintain an image map (https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/image/v1/image/_cq_editConfig.xml#L69) this is not considered during rendering. I.e. the HTL script does not include any logic to include an image map (i.e. `usemap` attribute or `map` elements).

**Comment by raducotescu** [comment]
@B3r, we've put the Image Map feature back on our roadmap, however it's not as simple as it looks with the Core Image component, given that the image that will get rendered is chosen by the client, given the width of the display container. Therefore you risk that a map defined on an author instance has totally different coordinates than the map would have on the final rendered image.

**Comment by gabrielwalt** [comment]
(CQ-4203499)
