### ISSUE TITLE
Text: The IPE config for paraformat is invalid

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-core-wcm-components#42]
Although the text component's editConfig has some rteplugins configured, e.g. "paraformat" in https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/text/v1/text/_cq_editConfig.xml#L20, this option is not provided in the according in-place editors toolbar. See also this scren
<img width="888" alt="inplace_editor_configuration" src="https://user-images.githubusercontent.com/185025/27421515-03a2c81c-572b-11e7-822b-8be08c9cfe8d.png">

**Comment by kwin** [comment]
This is probably due to the missing features attribute in the paraformat element.

**Comment by kwin** [comment]
The same is true for `miscconfig` which also lacks the mandatory `features` attribute.

**Comment by raducotescu** [comment]
@kwin, the configuration is not invalid - it just doesn't enable all features. If you need more than the default provided ones then you can create a content policy and enable them. Feel free to reopen the issue in case you still think the configuration should be addressed differently.

**Comment by kwin** [comment]
I would strongly suggest to use the same style to indicate that something needs to be enabled via the content policy first. Partly this is indicated via `features="-"` and partly by omitting the `features` attribute at all.
