### ISSUE TITLE
Need an imagetext core component

### ISSUE THREAD

**Issue by brianrush** [Adobe-Marketing-Cloud/aem-core-wcm-components#45]
I used the WCM Foundation imagetext component instead, but would like to have used a Core equivalent.

**Comment by henrykuijpers** [comment]
Why not create a composite component (containing a text and image component)?

**Comment by brianrush** [comment]
Not sure how to go about that.

**Comment by brianrush** [comment]
I'd found [Fixed Aggregate Component (i.e. TextImage)](https://forums.adobe.com/thread/2346635) but it was not what I'm after.

**Comment by gabrielwalt** [comment]
I don't think that we want something like a text-image component as this can be achieved with the responsive grid instead. However, I agree that we should provide a good example of how such a compound can be made possible.
