### ISSUE TITLE
As soon as v2 of a component is created, we will run into problems with client libraries

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Marketing-Cloud/aem-core-wcm-components#47]
I.e. https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/form/button/v1/button/clientlibs/editor/.content.xml

As soon as we create v2 of this button component, it will again have a clientlib category of cq.authoring.dialog - Causing 2 client libraries to be loaded (and in this case 2 validators to be registered)

**Comment by kwin** [comment]
Isn't this a duplicate of #15?

**Comment by raducotescu** [comment]
@kwin yes, it is.
