### ISSUE TITLE
Image: Include a last modification date even in publish image urls

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-core-wcm-components#48]
To allow to set a very long TTL for image urls it would be beneficial if at least optionally the publish URL (https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/image/v1/image#url-formats) includes a last modification date of the component's node as well (similar to what we have on the author already). That way it is assured that the URL changes whenever the image changes (which will automatically invalidate the cache entry)

**Comment by gabrielwalt** [comment]
+1, we added that to our roadmap.

**Comment by kwin** [comment]
@bpauli Can you adjust the section in the readme as well (https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/image/v1/image/README.md#url-formats)?

**Comment by bpauli** [comment]
@kwin Sure, thanks for the hint!
