### ISSUE TITLE
Unit testing classes are not available in jar 

### ISSUE THREAD

**Issue by shajiahmed** [Adobe-Marketing-Cloud/aem-core-wcm-components#49]
Couple of java class files from unit testing src/test/java are not available, few of them are from
com.adobe.cq.wcm.core.components.context
Can't use classes from this package, they may not be available at adobe repo as well its not included in jar file as well

**Comment by vladbailescu** [comment]
@shajiahmed, which classes are not available, the ``io.wcm.testing.mock.aem.junit.*`` package? That's available at http://wcm.io/testing/ and https://mvnrepository.com/artifact/io.wcm/io.wcm.testing.aem-mock

**Comment by shajiahmed** [comment]
wcm.io test classes start with package io.wcm.testing 
for core components there are test classes starting with package com.adobe.cq.core.components
I checked in repo it is not found in jar file as well. Files from the following src/test/java are missing
https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/tree/master/bundles/core/src/test/java/com/adobe/cq/wcm/core/components
I found this while trying to use the following classes
com.adobe.cq.wcm.core.components.context.CoreComponentTestContext;
com.adobe.cq.wcm.core.components.context.MockStyle;

**Comment by justinedelson** [comment]
I'm not sure these classes are intended for reuse by other proejcts. If so, one of the approaches documented in https://maven.apache.org/plugins/maven-jar-plugin/examples/create-test-jar.html should be followed.

**Comment by bpauli** [comment]
Hi @shajiahmed,

as @justinedelson mentioned this classes are not intended to use outside of the project and there is currently no plan to include this classes inside the jar.

If you want to use this classes inside your project you should duplicate / adapt this classes inside of your project.
