### ISSUE TITLE
Form components are hidden

### ISSUE THREAD

**Issue by shajiahmed** [Adobe-Marketing-Cloud/aem-core-wcm-components#50]
I see these form components are under group .core-wcm-form , they are not available for drag and drop options. It may be meant for drag and drop options. 
--

**Comment by justinedelson** [comment]
The core components are not directly usable by design. You need to create proxy components for the specific components you want to use. See https://docs.adobe.com/docs/en/aem/6-3/develop/components/core-components/using.html for details.
