### ISSUE TITLE
Incorrect spelling - sortOrder node list settings options in List dialog

### ISSUE THREAD

**Issue by gwilkins-btes** [Adobe-Marketing-Cloud/aem-core-wcm-components#51]
The node 

`/apps/core/wcm/components/list/v1/list/cq:dialog/content/items/tabs/items/listSettings/items/column/items/sortOreder` 

should be spelt 

`/apps/core/wcm/components/list/v1/list/cq:dialog/content/items/tabs/items/listSettings/items/column/items/sortOrder`

**Comment by bpauli** [comment]
@gwilkins-btes Thanks for reporting this typo.
