### ISSUE TITLE
Clearer separation between author and publish client libraries

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-core-wcm-components#53]
Currently both author-only as well as author/publish client libraries are having category names which don't allow to tell on which instance they should be loaded.

Examples:
- Category `core.wcm.components.page.v1.sharing` (https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/page/v1/page/clientlibs/sharing) seems relevant on publish and author.
- Category `core.wcm.page.properties` (https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/page/v1/page/clientlibs/properties) seems only relevant on publish.

I think it would be good to follow the AEM naming schema that all client libraries which are only relevant for authoring (i.e. should only be loaded for `WCMMode != disabled`) should have a category name starting with `cq.`  (examples in AEM are `cq.wcm.edit` or `cq.authoring.page`)

**Comment by gabrielwalt** [comment]
Meanwhile, we clarified through better naming conventions which clientlibs are for the editor and which are for publish. One exception however is the sharing clientlib of the page component where we didn't follow the convention, this should be fixed.

**Comment by kwin** [comment]
Why has this issue been closed without any related commit or comment? If I understood @gabrielwalt correctly in his previous comment he agreed that at least the category name of https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/page/v1/page/clientlibs/sharing/.content.xml should be changed, but this happened neither on master nor on develop branch. Apart from that it would be very helpful if you could somewhere write down the mentioned naming convention.

**Comment by richardhand** [comment]
Apologies @kwin, should have identified the change before closing. For the v2 page component we have moved the below `/site` following the convention of other components. See: https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/tree/development/content/src/content/jcr_root/apps/core/wcm/sandbox/components/page/v2/page/clientlibs/site/sharing

**Comment by vladbailescu** [comment]
This was fixed in release 2.0.0, author-specific clientLibs are postfixed with `.editor` to distinguish them. For example: https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/image/v2/image#client-libraries
