### ISSUE TITLE
Document the client library categories per component

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-core-wcm-components#54]
Currently a lot of Core components require client libraries (e.g. https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/page/v1/page/clientlibs, https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/form/container/v1/container/clientlibs, https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/list/v1/list/clientlibs). Those categories are not mentioned in the readme for each of those component. It would be really helpful to add those, as those need to be included as well to make the component fully working. The only reference to it I could find is in https://docs.adobe.com/docs/en/aem/6-3/develop/components/core-components/using.html#Load the Core Styles, but I think it is rather reasonable to document it here at github to be able to adjust this from release to release.

**Comment by gabrielwalt** [comment]
Meanwhile, we clarified through better naming conventions which clientlibs are for the editor and which are for publish, but I agree that the components' readme should also document those clientlibs.

The sharing clientlib of the page component seems to be an exception where we didn't follow the convention, which should be fixed.

**Comment by richardhand** [comment]
relates to: https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/issues/53 regarding documentation of clientLib naming approach for core components.

**Comment by vladbailescu** [comment]
This was fixed in release 2.0.0, see https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/title/v2/title#client-libraries for example
