### ISSUE TITLE
[v1.0.6 - Forms Container] Does not appear on page when added

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Marketing-Cloud/aem-core-wcm-components#55]
When adding the Forms Container Component (v1.0,6) to a v1.0.6/page derived Page in AEM, the Container does not display, or allow other Forms components to be dragged into it.

- When viewing the resulting node structure of the page, the container resource exists. 
- When i manually move form components (ex. text field) to be UNDER the container component, then the container renders on the page, and i can edit it (set its action etc.)
- However I cannot re-arrange form components IN the container, nor can i add new Form components to the now visible container component.

I assume it should work similarly to the layout container, where it will create a drop-zone within it, at which point I could add a layout container for complex layouts, or simply drag in forms components.

**Comment by gabrielwalt** [comment]
Thank you @davidjgonzalez, we'll look into this.
