### ISSUE TITLE
Smart Image : Multiple calls in Firefox and IE

### ISSUE THREAD

**Issue by kanika1901kapoor** [Adobe-Marketing-Cloud/aem-core-wcm-components#58]
In smartimage  there seems to be 2 image requests going - first call for image without rendition and the second call for image with viewport specific rendition.  First call does not get any response status and Response size is 0B while the second call gets a response status as 200 and response size is as expected. This issue is seen in IE and Firefox.

Url of first call - /content/project/us/en/pages/_jcr_content/root/my_page/par/responsivegrid/image_1.img.jpg

Url of second call - /content/project/us/en/pages/jcr%3acontent/root/my_page/par/responsivegrid/image_1.img.1200.jpg

**Comment by gabrielwalt** [comment]
Thank you @kanika1901kapoor, we'll look into this.

**Comment by raducotescu** [comment]
@kanika1901kapoor, can you please provide more details about how to reproduce this? A content package with a page component on which you added the image component would work.

I was not able to reproduce the problem, therefore I suspect that you somehow load a client library two times by accident.
