### ISSUE TITLE
Page thumbnail upload image not working

### ISSUE THREAD

**Issue by awadheshv** [Adobe-Marketing-Cloud/aem-core-wcm-components#59]
Page thumbnail upload image from page properties is not working. nothing happens after clicking on "Upload Image" and selecting an image. no indication of any error in browser console and it seems no upload request is being made to AEM.

reverting to v1.0.4 fixes this issue.

**Comment by richardhand** [comment]
@awadheshv - we've been unable to replicate this issue on AEM 6.3 General Availability with both v1.0.6 and v1.0.4.

Please reopen the issue if it's still a problem for you, answering the additional questions below:

• Do you see the same problem cross-browser?
• Are you editing the page properties from the Sites console or the Editor? Or is the problem seen in both locations?
• Is there any other information that you think may help us in replicating?

**Comment by awadheshv** [comment]
Hi @richardhand thank for looking into this, I can confirm that on a vanilla instance this issue is not reproducible with we retail content. I incorrectly assumed this to be an issue with new version since it works with 1.0.4
