### ISSUE TITLE
Do not use Page objects in API interfaces for link targets

### ISSUE THREAD

**Issue by stefanseifert** [Adobe-Marketing-Cloud/aem-core-wcm-components#64]
In the first released version of the List API and Breadcrumb/NavigationItem API a "Page" object was used for expressing the link target of the liste item/breadcrumb item. In my point of view this is bad API design because:
* It breaks separation of concern because it leaves the building of the final URL (e.g. extending ".html") to the view (HTL)
* It ignores the fact that pages may be redirect pages pointing to another link target e.g. an external URL

I've seen in the sandbox that the NavigationItem interface was already extended to also support a "getURL" method. The List interface is still unchanged, perhaps it should return a collection of NavigationItems instead of a collection of Pages.

Please also consider that a simple URL string may not be enough either. It may be desirable to specify further options e.g. a target property for opening an external link a new windows/tab, or special properties for tracking, or a anchor name for navigation to a specific paragraph in a page. Thus a flexible structure for describing a link target would be useful instead of a single Page or String argument.

See [wcm.io Link Handler API](http://wcm.io/handler/link/) for an example.

**Comment by richardhand** [comment]
Thanks @stefanseifert - your suggestion for abstraction of the items return type for the List component is now on our radar.

**Comment by vladbailescu** [comment]
Starting with release 2.0.0 a [ListItem](https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/master/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/models/ListItem.java) was introduced as a common base for components that return lists.

**Comment by gabrielwalt** [comment]
(CQ-4221281)

**Comment by gabrielwalt** [comment]
(CQ-4221281)
