### ISSUE TITLE
Content authors cannot read text "config" node

### ISSUE THREAD

**Issue by kele23** [Adobe-Marketing-Cloud/aem-core-wcm-components#66]
I customize the "text" component by copying it in my project. Specifically, my edits related to the default enabled plugins during editing.
Everything works if you are Admin, but if you use an user member of "content-authors" group (or more specifically "contributor" group), you can't see any customization, so you cannot use configured plugins.

_Admin_
![image](https://user-images.githubusercontent.com/3380263/30319559-848f48e0-97b0-11e7-894e-1c926710cf6d.png)
_Content Author_
![image](https://user-images.githubusercontent.com/3380263/30319497-569a2306-97b0-11e7-9069-3711207b0107.png)

I think this problem is due to a too restrictive deny permission that prevents users from reading the configuration of the inplace editing node (**apps/\*/config/\***)

![image](https://user-images.githubusercontent.com/3380263/30319688-cb808ec6-97b0-11e7-99fc-39f26d9d6d35.png)

I think it's necessary to change the text component by using a configuration structure like this:

![image](https://user-images.githubusercontent.com/3380263/30318357-2f9f436a-97ad-11e7-9741-288e4c2752db.png)

**Comment by richardhand** [comment]
Thanks @kele23 for your report - we can confirm the described behavior. The solution you provide solves the issue, however, it should work with the existing config set up, as documented at https://docs.adobe.com/docs/en/aem/6-3/administer/operations/page-authoring/rich-text-editor.html.

Therefore this is seen more as an AEM product issue. If you would like to follow-up you could create a support issue at https://helpx.adobe.com/marketing-cloud/contact-support.html

**Comment by richardhand** [comment]
@kele23 - I'm closing this issue given the previous comment regarding it being a product related issue.

**Comment by henrykuijpers** [comment]
I don't agree with this closing this ticket, I think putting a "configPath" with a value other than "config" is a perfect workaround for a product bug that is still not solved after all these years...

We have already created various tickets and never got Adobe Support to say "we'll fix this in the next version", so to this date the inplace editing feature is still broken when you configure the inplaceediting with a config node.

You'd say that Adobe having this problem in their own Core Components would make this get fixed easier, but apparently you're now closing this ticket even if you have a valid workaround + still not have the product bug fixed?

**Comment by henrykuijpers** [comment]
@richardhand Please reconsider this ticket.

**Comment by jurgenbrouwer** [comment]
I just followed the WKND tutorial. In this tutorial we extend the core components and I noticed that my "author" user has different options than my "admin" user. This is especially visible in full screen mode.

Admin (which is using the correct configuration):
![text-component-admin](https://user-images.githubusercontent.com/1295167/38311904-99b61b7a-3820-11e8-9f81-87eff0fc05db.png)

Author (which is using some sort of default configuration?):
![text-component-author](https://user-images.githubusercontent.com/1295167/38311905-99db43a0-3820-11e8-883d-37e114b7abb5.png)

This means you can't use the Core Text Component as it is intended.
