### ISSUE TITLE
Unable to use com.adobe.cq.wcm.core.components.internal.servlets.TextValueDataResourceSource.java - Not exported by bundle

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Marketing-Cloud/aem-core-wcm-components#68]
We should be able to use this class; Either it should be moved to a different package, or it should be exported (but the name "internal" implies that that was not the intention).

**Comment by richardhand** [comment]
@henrykuijpers - we see this class as an implementation detail, hence why it's not exported. Perhaps you could provide some more details on what you would like to use it for?

**Comment by henrykuijpers** [comment]
I don't want to duplicate that code in my own codebase (which we did right now), I would rather reuse that class. If it's really an implementation detail, I don't think the class should be public?

**Comment by richardhand** [comment]
that's correct, it shouldn't be publicly available. We will look into ensuring that's the case.

**Comment by jckautzmann** [comment]
This class (although declared public) is not publicly available as it is not exported by the bundle.

**Comment by raducotescu** [comment]
As mentioned by @jckautzmann, the class is not public, in the sense that it's not exported by the bundle.
