### ISSUE TITLE
subpackage instructions not working.

### ISSUE THREAD

**Issue by sasconsul** [Adobe-Marketing-Cloud/aem-core-wcm-components#73]
The core components are not being deployed as a subpackage.  I get the following message when using the instructions in the README.md.
`
[WARNING] No matching artifacts for Sub Packages: groupId=com.adobe.cq,artifactId=core.wcm.components.all,filter=true,excludeTransitive=false
`

Here are fragments of my ui.app/pom.xml:
```
					<subPackages>
						<subPackage>
							<groupId>com.adobe.acs</groupId>
							<artifactId>acs-aem-commons-content</artifactId>
							<filter>true</filter>
						</subPackage>
						<subPackage>
							<groupId>com.adobe.cq</groupId>
							<artifactId>core.wcm.components.all</artifactId>
							<filter>true</filter>
						</subPackage>
					</subPackages>
```
And the reactor pom.xml:
```
<dependency>
    <groupId>com.adobe.cq</groupId>
    <artifactId>core.wcm.components.core</artifactId>
    <version>1.0.6</version>
    <scope>provided</scope>
</dependency>
<dependency>
    <groupId>com.adobe.cq</groupId>
    <artifactId>core.wcm.components.all</artifactId>
    <type>zip</type>
    <version>1.0.6</version>
    <scope>provided</scope>
</dependency>
```

This is a problem in production mode.  I have to upload and install the **core.wcm.components** package directly.  

Also, I have tried to change my build to look like the we.retail build to no avail.  I am missing something?

**Comment by vladbailescu** [comment]
You will need to add the dependency to your `ui.app/pom.xml` as well:

```
<dependency>
    <groupId>com.adobe.cq</groupId>
    <artifactId>core.wcm.components.all</artifactId>
    <type>zip</type>
    <version>1.0.6</version>
    <scope>provided</scope>
</dependency>
```
