### ISSUE TITLE
Core WCM Components 1.1 not "compatible" with AEM 6.3 due to com.adobe.cq.export.json dependency

### ISSUE THREAD

**Issue by stefanseifert** [Adobe-Marketing-Cloud/aem-core-wcm-components#76]
the new version 1.1 of the core components cannot be installed on AEM 6.3 because this dependency is not fulfilled:
```
        <dependency>
            <groupId>com.adobe.cq</groupId>
            <artifactId>com.adobe.cq.export.json</artifactId>
            <version>0.0.12</version>
            <scope>provided</scope>
        </dependency>
```

i assume this is part of the "Content Fragment Updates and Content Services" feature pack which was published recently - but is this by intention that this FP has to be installed on all instances where the core components are used - regardless if the features of the FP are needed for the project or not?

at least such a dependency should be documented.

**Comment by vladbailescu** [comment]
Hi Stefan,

The enhanced JSON exporter is part of `cq-6.3.0-featurepack-19614` and will be part of the next service pack as well. The dependency was documented in the [release notes](https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-1.1.0):

> Added extended JSON Export annotations (requires `cq-6.3.0-featurepack-19614`)

Would it be more helpful if we included a table of requirements for each Core Components version at the top project's README? Like https://github.com/Adobe-Marketing-Cloud/aem-project-archetype#requirements

**Comment by stefanseifert** [comment]
fine for me - i think this should be listed on the readme in the root folder within the "System Requirements" section
https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components
