### ISSUE TITLE
Some components say 'production-ready' in the documentation, while they are not

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Marketing-Cloud/aem-core-wcm-components#80]
I.e. https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/form/text/v1/text
The documentation page says production-ready. 

But without working servervalidation, I believe you cannot consider this component production-ready.

**Comment by vladbailescu** [comment]
Validation is on our roadmap, see #56

**Comment by raducotescu** [comment]
@henrykuijpers, I think your issue duplicates #56.
