### ISSUE TITLE
Question: can page core component be used for static template? 

### ISSUE THREAD

**Issue by lbaoyu** [Adobe-Marketing-Cloud/aem-core-wcm-components#81]
Is it designed to be used for editable template only?
We.retail site use it only for editable template, not sure use it for static template is something been tested too.

**Comment by vladbailescu** [comment]
The page component is designed to be used only with editable templates: https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/page/v1/page/body.html#L16
