### ISSUE TITLE
Image cmp to use asset description, title and tags

### ISSUE THREAD

**Issue by bpauli** [Adobe-Marketing-Cloud/aem-core-wcm-components#82]
As an author, when adding an image to a page, if that image comes from the DAM and already has a title, a description, I want the image component to reuse that information, so that I don't need to re-enter it in the edit dialog of my image component.

* The alt text should be taken:
** from the image description if it is not empty
** from the image title if the description is empty
* The caption text should be taken:
** from the image title

h6. Requirements
* The author should have the possibility to preview the values coming from DAM, and either take them, or to overwrite them with custom values.
* The author should also have the possibility to revert the values to the ones coming from DAM.

**Comment by bpauli** [comment]
completed with https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/commit/9e1e9f387e2480b3639d470692d5357c6b751fca

**Comment by vladbailescu** [comment]
This was fixed in `v2` of the Image component: https://helpx.adobe.com/experience-manager/core-components/using/image.html#ConfigureDialog
