### ISSUE TITLE
Set Cache-Control header in the AdaptiveImageServlet

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-core-wcm-components#88]
Although with #48 the url of an image should change everytime when its content changes, this is not reflected via an appropriate Cache-Control response header. Please make sure that you send a long max-age Cache Control with each image response, whose request contained a timestamp-selector.

This especially becomes important since now the Dispatcher supports response header caching.

**Comment by vladbailescu** [comment]
Fixed in release 2.0.0
