### ISSUE TITLE
Deploy released artifacts to Maven Central and/or https://repo.adobe.com

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-core-wcm-components#9]
It would be very handy to have those artifacts not only downloadable as GitHub release but also from Maven Central and/or from the Adobe Maven Repository.

**Comment by bpauli** [comment]
We are currently working on getting this artifacts on our public nexus at repo.adobe.com.

I hope we can soon announce success...

**Comment by bpauli** [comment]
All artifacts are now public on repo.adobe.com

**Comment by kwin** [comment]
Great, thanks. Can you mention that in the readme?
