### ISSUE TITLE
FormConstants: What if we're at form container version 50?

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Marketing-Cloud/aem-core-wcm-components#93]
* Will RT_ALL_CORE_FORM_CONTAINER then contain 50 entries?
* Will RT_CORE_FORM_CONTAINER_V1 then be duplicated 50 times?
...

**Comment by gabrielwalt** [comment]
indeed, but at v50 it will be likely that v1-45 will be deprecated and or just not part anymore of the more recently released packages.
