### ISSUE TITLE
Options component: Wrap labels of checkbox/radio in <span>

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Marketing-Cloud/aem-core-wcm-components#95]
Please wrap the labels of the checkboxes and radio buttons in a span, so it is possible to add specific styling  to them.

https://stackoverflow.com/questions/5688712/is-there-a-css-selector-for-text-nodes

**Comment by gabrielwalt** [comment]
+1 this makes sense, and I think that we can do that change without needing to bump the major version of the component, despite some changes in the markup, because it won't affect existing style rules.
