### ISSUE TITLE
Include sources and javadocs in release

### ISSUE THREAD

**Issue by jsedding** [Adobe-Marketing-Cloud/aem-core-wcm-components#97]
Please include source and javadocs jars in releases and deploy them to maven central along with the binary jars. It is very helpful for quickly looking up javadocs, when developing in a modern IDE, or even during debugging. Thanks.

**Comment by raducotescu** [comment]
I've deployed the sources and javadoc jars now at https://repo.adobe.com/nexus/content/repositories/releases/com/adobe/cq/core.wcm.components.core/2.0.0/.

We will have to include the configurations for the Maven Javadoc Plugin and the Maven Source Plugin in the bundle's POM file. Thanks for the heads-up!
